targets:
  $default:
    sources:
      - $package$
      - lib/**
      - pubspec.yaml
    builders:
      json_serializable:
        options:
          checked: true
          create_to_json: true
          explicit_to_json: true
          field_rename: snake
          include_if_null: false
      pubspec_generator:
        options:
          output: lib/src/pubspec.yaml.g.dart
