name: scryfall_api
description: A wrapper of the Scryfall API for the Dart programming language.
version: 1.1.0
homepage: https://github.com/aroningruber/scryfall_api

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  http: ^0.13.4
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.1.3
  mocktail: ^0.3.0
  test: ^1.20.1
  lints: ^2.0.1
